# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Google Chrome
      run: |
        sudo apt update
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        google-chrome --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start local web server
      working-directory: ./dist
      run: |
        python3 -m http.server 8000 &
        sleep 5  # подождём, чтобы сервер успел подняться

    - name: Run tests
      env:
        CHROME_BIN: /usr/bin/google-chrome
      run: |
        pytest tests/ --tb=short --capture=tee-sys